# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dz\DZ3v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 500)

        self.smena = QtWidgets.QPushButton(Dialog)
        self.smena.setGeometry(QtCore.QRect(450, 440, 150, 32))
        self.smena.setStyleSheet("font: 12pt \"Rockwell Condensed\";")
        self.smena.setObjectName("smena")
        self.smena.setText("сменить местами")

        self.exitprog = QtWidgets.QPushButton(Dialog)
        self.exitprog.setGeometry(QtCore.QRect(450, 400, 150, 32))
        self.exitprog.setStyleSheet("font: 10pt \"Rockwell Condensed\";")
        self.exitprog .setObjectName("exitprog")
        self.exitprog.setText("выход из программы")

        self.writeName = QtWidgets.QPushButton(Dialog)
        self.writeName.setGeometry(QtCore.QRect(450, 20, 150, 31))
        self.writeName.setStyleSheet("font: 12pt \"Rockwell Condensed\";")
        self.writeName.setObjectName("writeName")

        self.myname = QtWidgets.QLabel(Dialog)
        self.myname.setGeometry(QtCore.QRect(180, 30, 191, 21))
        self.myname.setText("")
        self.myname.setObjectName("myname")

        self.raschet = QtWidgets.QPushButton(Dialog)
        self.raschet.setGeometry(QtCore.QRect(450, 240, 150, 31))
        self.raschet.setStyleSheet("font: 12pt \"Rockwell Condensed\";")
        self.raschet.setObjectName("raschet")

        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 80, 221, 150))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chislo = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.chislo.setObjectName("chislo")
        self.verticalLayout.addWidget(self.chislo)
        self.step = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.step.setObjectName("step")
        self.verticalLayout.addWidget(self.step)
        self.otvet = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.otvet.setObjectName("otvet")
        self.verticalLayout.addWidget(self.otvet)

        self.H_shag = QtWidgets.QLineEdit(Dialog)
        self.H_shag.setGeometry(QtCore.QRect(168, 338, 221, 22))
        self.H_shag.setObjectName("H_shag")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 338, 111, 20))
        self.label_5.setObjectName("label_5")
        self.raschet_shag = QtWidgets.QPushButton(Dialog)
        self.raschet_shag.setGeometry(QtCore.QRect(450, 340, 150, 31))
        self.raschet_shag.setStyleSheet("font: 10pt \"Rockwell Condensed\";")
        self.raschet_shag.setObjectName("raschet_shag")
        self.otvet_shag = QtWidgets.QLineEdit(Dialog)
        self.otvet_shag.setGeometry(QtCore.QRect(168, 378, 221, 22))
        self.otvet_shag.setText("")
        self.otvet_shag.setObjectName("otvet_shag")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 378, 111, 20))
        self.label_6.setObjectName("label_6")

        self.pervchislo = QtWidgets.QLabel(Dialog)
        self.pervchislo.setGeometry(QtCore.QRect(20, 408, 111, 20))
        self.pervchislo.setObjectName("pervchislo")

        self.vtoroechislo = QtWidgets.QLabel(Dialog)
        self.vtoroechislo.setGeometry(QtCore.QRect(20, 445, 111, 20))
        self.vtoroechislo.setObjectName("pervchislo")

        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 111, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.otvet_shag_2 = QtWidgets.QLineEdit(Dialog)
        self.otvet_shag_2.setGeometry(QtCore.QRect(168, 301, 221, 22))
        self.otvet_shag_2.setText("")
        self.otvet_shag_2.setObjectName("otvet_shag_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 261, 141, 20))
        self.label_7.setObjectName("label_7")

        self.H_shag_2 = QtWidgets.QLineEdit(Dialog)
        self.H_shag_2.setGeometry(QtCore.QRect(168, 261, 221, 22))
        self.H_shag_2.setObjectName("H_shag_2")

        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 301, 141, 20))
        self.label_8.setObjectName("label_8")

        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 301, 141, 20))
        self.label_8.setObjectName("label_8")

        self.chislo1 = QtWidgets.QLineEdit(Dialog)
        self.chislo1.setGeometry(QtCore.QRect(168, 410, 221, 22))
        self.chislo1.setText("")
        self.chislo1.setObjectName("chislo1")

        self.chislo2 = QtWidgets.QLineEdit(Dialog)
        self.chislo2.setGeometry(QtCore.QRect(168, 445, 221, 22))
        self.chislo2.setText("")
        self.chislo2.setObjectName("chislo2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.writeName.setText(_translate("Dialog", "щёлкните здесь!"))
        self.raschet.setText(_translate("Dialog", "Расчитать "))
        self.label_5.setText(_translate("Dialog", "Введите шаг"))
        self.raschet_shag.setText(_translate("Dialog", "Расчитать с шагом"))
        self.label_6.setText(_translate("Dialog", "Ответ"))
        self.label_2.setText(_translate("Dialog", "введите число"))
        self.label_3.setText(_translate("Dialog", "введите Степень"))
        self.label_4.setText(_translate("Dialog", "ответ"))
        self.label_7.setText(_translate("Dialog", "Введите первую границу"))
        self.label_8.setText(_translate("Dialog", "Введите вторую границу"))
        self.pervchislo.setText(_translate("Dialog", "Первое Число"))
        self.vtoroechislo.setText(_translate("Dialog", "Второе Число"))

        #кнопка расчёта x**2
        self.raschet.clicked.connect(self.result)

        #кнопка расчёта X**2 на отрезке
        self.raschet_shag.clicked.connect(self.result_sshagom)

        #кнопка вывода имени
        self.writeName.clicked.connect(self.printmyname)

        #кнопка смены значений
        self.smena.clicked.connect(self.smenaCh)

        #выход
        self.exitprog.clicked.connect(self.viihod)

    # logic for programm
    def result (self):
        x = float (self.chislo.text())
        stepen = float (self.step.text())
        otvet_not_H = str( x**stepen)
        self.otvet.setText(otvet_not_H)
#
    def result_sshagom (self) :
        x1 = int(self.chislo.text())
        otvet_s_shagom = " "
        LeftGR = int (self.H_shag_2.text())
        rightGR = int (self.otvet_shag_2.text())
        shag = int (self.H_shag.text())
        t=1

        while LeftGR <= rightGR :
            t = t * x1
            LeftGR += shag
            otvet_s_shagom = str(otvet_s_shagom)+ "; " + str(t)

        self.otvet_shag.setText(otvet_s_shagom)
#
    def printmyname (self):
        self.myname.setText('Гудовских Георгий Андреевич')

    def smenaCh (self):
        pervoechis = str (self.chislo1.text())
        vtoroechis = str (self.chislo2.text())


        self.chislo1.setText(vtoroechis)
        self.chislo2.setText(pervoechis)

    def viihod (self):
        exit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
