# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dz\DZ3v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.writeName = QtWidgets.QPushButton(Dialog)
        self.writeName.setGeometry(QtCore.QRect(490, 20, 131, 31))
        self.writeName.setStyleSheet("font: 12pt \"Rockwell Condensed\";")
        self.writeName.setObjectName("writeName")
        self.myname = QtWidgets.QLabel(Dialog)
        self.myname.setGeometry(QtCore.QRect(180, 30, 131, 21))
        self.myname.setText("")
        self.myname.setObjectName("myname")
        self.raschet = QtWidgets.QPushButton(Dialog)
        self.raschet.setGeometry(QtCore.QRect(490, 240, 131, 31))
        self.raschet.setStyleSheet("font: 12pt \"Rockwell Condensed\";")
        self.raschet.setObjectName("raschet")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 90, 221, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.chislo = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.chislo.setObjectName("chislo")

        self.verticalLayout.addWidget(self.chislo)
        self.step = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.step.setObjectName("step")
        self.verticalLayout.addWidget(self.step)
        self.otvet = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.otvet.setObjectName("otvet")
        self.verticalLayout.addWidget(self.otvet)
        self.H_shag = QtWidgets.QLineEdit(Dialog)
        self.H_shag.setGeometry(QtCore.QRect(130, 290, 221, 22))
        self.H_shag.setObjectName("H_shag")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 111, 20))
        self.label_5.setObjectName("label_5")
        self.raschet_shag = QtWidgets.QPushButton(Dialog)
        self.raschet_shag.setGeometry(QtCore.QRect(490, 340, 131, 31))
        self.raschet_shag.setStyleSheet("font: 10pt \"Rockwell Condensed\";")
        self.raschet_shag.setObjectName("raschet_shag")
        self.otvet_shag = QtWidgets.QLineEdit(Dialog)
        self.otvet_shag.setGeometry(QtCore.QRect(130, 330, 221, 22))
        self.otvet_shag.setText("")
        self.otvet_shag.setObjectName("otvet_shag")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 330, 111, 20))
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 111, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "dz3v1"))
        self.writeName.setText(_translate("Dialog", "щёлкните здесь!"))
        self.raschet.setText(_translate("Dialog", "Расчитать "))
        self.label_5.setText(_translate("Dialog", "Введите шаг"))
        self.raschet_shag.setText(_translate("Dialog", "Расчитать с шагом"))
        self.label_6.setText(_translate("Dialog", "Ответ"))
        self.label_2.setText(_translate("Dialog", "введите число"))
        self.label_3.setText(_translate("Dialog", "введите Степень"))
        self.label_4.setText(_translate("Dialog", "ответ"))
        #кнопка расчёта x**2
        self.raschet.clicked.connect(self.result)

        #кнопка расчёта X**2 на отрезке
        self.raschet_shag.clicked.connect(self.result_shagom)


    # logic for programm
    def result (self):
        x = float (self.chislo.text())
        stepen = float (self.step.text())
        otvet_not_H = str( x**stepen)
        self.otvet.setText(otvet_not_H)

    def result_shagom (self):




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
